Add:user.views.py 추가
wecode-bootcamp-korea/13-Winted-backend pull request #4
Opened 2020-11-06 01:19 UTC by JypYong

회원가입 , 로그인 , 좋아요 , 중복체크 기능

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- unit test 미구현 . 로그인, 회원가입, 좋아요 , 중복체크 기능 구현. 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-11 07:55 UTC, lordmyshepherd requested changes

2020-11-11 07:55 UTC, lordmyshepherd commented on user/utils.py
> +            user_id     = jwt.decode(encode_token, SECRET, algorithm = ALGORITHM)
jwt.decode() 함수가 실행되면 access_token의 payload 부분의 값이 복호화되어 리턴됩니다.
그렇게 때문에 user_id라는 변수에 지정하는 것 보다는 payload에 할당해주는 것이 명확합니다.

```suggestion
            payload = jwt.decode(encode_token, SECRET, algorithm = ALGORITHM)                         
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/utils.py
> +                return func(self, request,*args ,**kwargs)
```suggestion
            user = User.objects.get(id=payload["user_id"])
            request.user = user
            return func(self, request,*args ,**kwargs) 
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/utils.py
> +                return func(self, request,*args ,**kwargs)
get() method를 사용할 때 user가 존재하지 않는 경우 UserDoseNotExist Error가 발생합니다.
그렇기 때문에 if문을 사용할 필요가 없습니다. 
이미 line 31에서 get()에서 발생할 수 있는 error를 잡아주고 있기 때문입니다.

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            get_user_id     = User.objects.get(id=user_id).id
이미 user 인스턴스에서 id 값을 불러오고 있기 때문에 한번 더 User.objects.get()을 사용할 필요가 없습니다.
```suggestion
            user_id = request.user.id
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            get_company_id  = Company.objects.get(id=company_id).id
변수명은 명사로 작성해주셔야 됩니다.
```suggestion
            company_id  = Company.objects.get(id=company_id).id
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            like_filter     = Like.objects.filter (user_id = get_user_id , company_id=get_company_id)
```suggestion
            like_filter     = Like.objects.filter (user_id = user_id , company_id=company_id)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            like_filter     = Like.objects.filter (user_id = get_user_id , company_id=get_company_id)
```suggestion
            likes     = Like.objects.filter (user_id = get_user_id , company_id=get_company_id)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({"message":"user_id or company_id INVALID"},status=400)
```suggestion
            return JsonResponse({"message":"company_id INVALID"},status=400)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            data            = json.loads(request.body)
json decode error 핸들링 필요

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            get_user_id     = User.objects.get(id=user_id).id
```suggestion
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +                return JsonResponse({"message":"SUCCESS"},status=201)
```suggestion
                return JsonResponse({"message":"NO_CONTENT"}, status=204)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for applied_status in  User.objects.get(id=user_id).likes.select_related('district__city', 'compensation', 'response_rate')]
1. select_related()를 왜 사용하셨나요?

2. select_related()는 정참조일 때 사용하나요? 역참조 일 때 사용하나요? 

3. 사용하게되면 어떤점이 장점인가요?

hit) 한번에 다른 테이블 데이터까지 가져옴???

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for applied_status in  User.objects.get(id=user_id).likes.select_related('district__city', 'compensation', 'response_rate')]
성능 향상 측면

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for tags in  User.objects.get(id=user_id).tag_filters.select_related()]
여기서는 왜 select_related()에 인자로 아무것도 전달하지 않으셨나요?

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for tags in  User.objects.get(id=user_id).tag_filters.select_related()]
차이점이 무엇인지!

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for tags in  User.objects.get(id=user_id).tag_filters.select_related()]
참고로 여기서는 select_related()를 사용하지 않으셔도 됩니다.

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for district in  User.objects.get(id=user_id).district_filters.select_related()]
👍 
마찬가지로 여기서는 왜 select_related()에 인자로 아무것도 전달하지 않으셨나요?

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            } for career in  User.objects.get(id=user_id).career_filters.select_related()]
사실상 select_related를 사용하지 않으셔도 결과와 성능은 같습니다!

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +        return JsonResponse( {"message":"SUCCESS","tag_list":tag_list , "district_list" :district_list ,"career_list" :career_list},status=201)
```suggestion
        return JsonResponse( {"message":"SUCCESS","tag_list":tag_list , "district_list" :district_list ,"career_list" :career_list},status=200)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +        filter_delete       = User.objects.get(id=user_id)
같은 동작을 하는 코드가.... 있어보입니다.. 다시 한번 생각해보시고 수정해보세요!

```suggestion
        user_id                = request.user.id   
        get_user_id         = User.objects.get(id=user_id).id
        filter_delete         = User.objects.get(id=user_id)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +        usertagfilter_table = User.objects.get(id=user_id).usertagfilter_set.all()
```suggestion
        user_tag_filters = User.objects.get(id=user_id).usertagfilter_set.all()
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +                    filter.delete()
```suggestion
            for user_tag_filter in UserTagFilter.objects.filter(user_id=user_id):
                if user_tag_filter.tag.id not in tag_list:
                    filter.delete()
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +                    )
`UserTagFilter.objects.filter(user_id=user_id, tag_id=tag).exists()`
exist()함수가 실행될 때, database hit 1번!

생성할 때, hit 1번
```
UserTagFilter.objects.create(
                        user_id = user_id,
                        tag_id  = tag
                    )

```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +            for filter in UserTagFilter.objects.filter(user_id=user_id):
`UserTagFilter.objects.filter(user_id=user_id)`
여기서 database hit 1번

`filter.tag.id`
여기서, for문이 순차적으로 실행될 때 마다 filter에 연결된 tag table을 조회하게 되는데, 이때마다 datbase hit!!

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +                    UserDistrictFilter.objects.create(user_id= user_id, district_id = district)
```python
if  data.get('district_list') :
    UserDistrictFilter.objects.filter(user_id=user_id).delete()
    for district in district_list:
        UserDistrictFilter.objects.create(user_id=user_id, district_id)
```

2020-11-11 07:55 UTC, lordmyshepherd commented on user/views.py
> +                    UserDistrictFilter.objects.create(user_id= user_id, district_id = district)
**additional comment
bulk_create() method를 사용하면 for문 없이 한번에 UserDistrictFilter들을 한번의 query로 생성할 수 있습니다.

2020-11-12 13:16 UTC, JypYong commented on user/views.py
> +            } for applied_status in  User.objects.get(id=user_id).likes.select_related('district__city', 'compensation', 'response_rate')]
1. Select 문을 줄이고 가독성을 높이기위해 . inner join하여서 가독성 up! 
2. 정참조 . 
3. 1번과 같은 이유 !

2020-11-12 13:16 UTC, JypYong commented on user/views.py
> +            } for tags in  User.objects.get(id=user_id).tag_filters.select_related()]
여기서는 왜 select_related()에 인자로 아무것도 전달하지 않으셨나요? 

category_id 의 1개의 인자밖에 없어서 . 적지 않았습니다 . 
위에껀 'district__city', 'compensation', 'response_rate'의 인자와  상위 카테고리를 참조하는 링크가 있는데 3개의 인자만 사용하여 3개만 적었습니다 . . . 

차이점이 무엇인지! 
() 요거는 Select_related의 정참조하기위한 값을 다 가져옴 . 
(인자) 를 결정해주면  해당 인자로만 정참조된 값을 가져옴 . 

참고로 여기서는 select_related()를 사용하지 않으셔도 됩니다. 
!?  ...

2020-11-12 13:16 UTC, JypYong commented on user/views.py
> +            } for tags in  User.objects.get(id=user_id).tag_filters.select_related()]
https://aquerytool.com:443/aquerymain/index/?rurl=0833fe94-a4a2-493a-8b56-24854ce9f710
63q44t

2020-11-12 13:16 UTC, JypYong commented on user/views.py
> +            } for district in  User.objects.get(id=user_id).district_filters.select_related()]
위와 같은 이유입니다 .

2020-11-12 13:16 UTC, JypYong commented on user/views.py
> +            } for career in  User.objects.get(id=user_id).career_filters.select_related()]
?!?!?!?!?!??! 잘모르겠습니다 ㅠ

2020-11-12 13:18 UTC, lordmyshepherd approved these changes

2020-11-12 13:18 UTC, lordmyshepherd commented on user/utils.py
> +            user_id     = jwt.decode(encode_token, SECRET, algorithm = ALGORITHM)
**필수**

2020-11-12 13:18 UTC, lordmyshepherd commented on user/utils.py
> +                return func(self, request,*args ,**kwargs)
필수

2020-11-12 13:18 UTC, lordmyshepherd commented on user/views.py
> +            get_user_id     = User.objects.get(id=user_id).id
필수

2020-11-12 13:18 UTC, lordmyshepherd commented on user/views.py
> +            get_company_id  = Company.objects.get(id=company_id).id
필수

2020-11-12 13:18 UTC, lordmyshepherd commented on user/views.py
> +            like_filter     = Like.objects.filter (user_id = get_user_id , company_id=get_company_id)
필수

2020-11-12 13:18 UTC, lordmyshepherd commented on user/views.py
> +            like_filter     = Like.objects.filter (user_id = get_user_id , company_id=get_company_id)
필수

2020-11-12 13:18 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({"message":"user_id or company_id INVALID"},status=400)
필수

2020-11-12 13:19 UTC, lordmyshepherd commented
재용님 수고 많으셨어요~
LGTM 👍

2020-11-12 13:19 UTC, merged