[김형욱] feature/resume
wecode-bootcamp-korea/13-Winted-backend pull request #6
Opened 2020-11-09 08:20 UTC by kho5420

- 탐색페이지(카테고리,필터리스트,회사공고 리스트,회사공고 상세페이지,회사 리스트 필터링)
- 이력서페이지(이력서리스트, 이력서상세정보, 스펙 등록/삭제)

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 탐색페이지
- 이력서페이지
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 탐색페이지(카테고리,필터리스트,회사공고 리스트,회사공고 상세페이지,회사 리스트 필터링)
- 이력서페이지(이력서리스트, 이력서상세정보, 스펙 등록/삭제)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-10 08:01 UTC, ulfrid requested changes
확인 부탁드립니다.

2020-11-10 08:01 UTC, devops-andrew commented on company/models.py
> +    image_url            = models.CharField(max_length=500)
```suggestion
    image_url            = models.URLField(max_length=2000)
```
길이는 더 여유있게 주셔도 좋습니다. URLField는 사실 form을 사용할때 validation의 의미가 있는 필드지만, 장고에서 지원해주는 필드로 유의미 하게 위코드에서는 컨벤션으로서 적용하는것을 권장드립니다.  변경해주세요.

2020-11-10 08:01 UTC, ulfrid commented on company/views.py
위의 로직은 login_check 라는 데코레이터를 생성해서 데코레이터를 통해서 유저 로그인 여부를 판별하면 더 간결하게 작성할 수 있을것 같습니다.  token_check데코레이터와 달리 토큰이 없으면 에러처리 하지말고, None을 전달해주세요.

2020-11-10 08:01 UTC, ulfrid commented on resume/views.py
> +        except ValueError as ex:
전체적으로 ValueError Exception을 처리하고 계신데 이유를 알고 싶습니다.

2020-11-10 10:23 UTC, kho5420 commented on company/models.py
> +    image_url            = models.CharField(max_length=500)
넵 수정했습니다.

2020-11-10 10:37 UTC, kho5420 commented on company/views.py
데코레이터랑 코드부분 수정했습니다

2020-11-10 10:39 UTC, kho5420 commented on resume/views.py
> +        except ValueError as ex:
뭔가 try excpet 부분에 예외처리를 해주고싶었는데 get 메소드라서 Keyerror는 없고 그냥 Exception을 쓰자니 너무 광범위한거같아서 ValueError를 사용을했습니다. 혹시 어떤걸로 바꾸는게 괜찮을까요??

2020-11-10 14:32 UTC, ulfrid commented on resume/views.py
> +        except ValueError as ex:
특별히 지금상황에서 에러 처리할게 발견되지 않았으면 필요하지 않은이상 오히려 생략하는게 좋을것 같습니다. 확인되지 않은 에러를 위해 작성해두는건 코드를 처음보는 사람에게 의미파악을 하는 시간을 들이게 되어 경제적이지 않은것 같습니다. 불필요한 익셉션 제거 해주시면 머지하겠습니다 수고하셨습니다

2020-11-11 01:57 UTC, kho5420 commented on resume/views.py
> +        except ValueError as ex:
리뷰 감사드립니다. 불필요한 익셉션 제거했습니다~

2020-11-11 02:39 UTC, ulfrid commented
LGTM

2020-11-11 02:39 UTC, merged